In [14]:
def findNum():
    result_list = []
    for num in range(2000, 3200):  
        #print (num)
        if num % 7 == 0 and num % 35 != 0 :
            result_list.append(num)
    return result_list

In [15]:
print(findNum())

[2002, 2009, 2016, 2023, 2037, 2044, 2051, 2058, 2072, 2079, 2086, 2093, 2107, 2114, 2121, 2128, 2142, 2149, 2156, 2163, 2177, 2184, 2191, 2198, 2212, 2219, 2226, 2233, 2247, 2254, 2261, 2268, 2282, 2289, 2296, 2303, 2317, 2324, 2331, 2338, 2352, 2359, 2366, 2373, 2387, 2394, 2401, 2408, 2422, 2429, 2436, 2443, 2457, 2464, 2471, 2478, 2492, 2499, 2506, 2513, 2527, 2534, 2541, 2548, 2562, 2569, 2576, 2583, 2597, 2604, 2611, 2618, 2632, 2639, 2646, 2653, 2667, 2674, 2681, 2688, 2702, 2709, 2716, 2723, 2737, 2744, 2751, 2758, 2772, 2779, 2786, 2793, 2807, 2814, 2821, 2828, 2842, 2849, 2856, 2863, 2877, 2884, 2891, 2898, 2912, 2919, 2926, 2933, 2947, 2954, 2961, 2968, 2982, 2989, 2996, 3003, 3017, 3024, 3031, 3038, 3052, 3059, 3066, 3073, 3087, 3094, 3101, 3108, 3122, 3129, 3136, 3143, 3157, 3164, 3171, 3178, 3192, 3199]


In [2]:
import numpy as np 

In [2]:
a = np.array([2,3,4])

In [3]:
type(a)

numpy.ndarray

In [4]:
a.ndim

1

In [5]:
a.shape

(3,)

In [30]:
b = np.array([[3, 8, 7],[9,3,5],[5,2,4],[6,7,2]])
b

array([[3, 8, 7],
       [9, 3, 5],
       [5, 2, 4],
       [6, 7, 2]])

In [32]:
b2 = np.exp(b)/np.sum(b, axis=1)
b2

ValueError: operands could not be broadcast together with shapes (4,3) (4,) 

In [29]:
b = b/np.sum(b, keepdims=True, axis=1)
b

array([[0.16666667, 0.44444444, 0.38888889],
       [0.52941176, 0.17647059, 0.29411765],
       [0.45454545, 0.18181818, 0.36363636],
       [0.4       , 0.46666667, 0.13333333]])

In [22]:
maxi = np.max(b, axis=1)

In [23]:
maxi

array([8, 9, 5, 7])

In [24]:
b-maxi[:,np.newaxis]

array([[-5,  0, -1],
       [ 0, -6, -4],
       [ 0, -3, -1],
       [-1,  0, -5]])

In [25]:
temp1 = np.exp(maxi)
temp1

array([2980.95798704, 8103.08392758,  148.4131591 , 1096.63315843])

In [19]:
b = np.exp(b-maxi[:,np.newaxis])

In [20]:
b

array([[0.00673795, 1.        , 0.36787944],
       [1.        , 0.00247875, 0.01831564],
       [1.        , 0.04978707, 0.36787944],
       [0.36787944, 1.        , 0.00673795]])

In [13]:
b = b/np.sum(b, keepdims=True, axis=1)

In [14]:
b

array([[0.00490169, 0.72747516, 0.26762315],
       [0.97962921, 0.00242826, 0.01794253],
       [0.70538451, 0.03511903, 0.25949646],
       [0.26762315, 0.72747516, 0.00490169]])

In [36]:
a1 = np.array([[3, 8, 7],[9,3,5],[5,2,4],[6,7,2]])
a1

array([[3, 8, 7],
       [9, 3, 5],
       [5, 2, 4],
       [6, 7, 2]])

In [38]:
a1 -= a1.max(axis=1).reshape(-1,1)
a1

array([[-5,  0, -1],
       [ 0, -6, -4],
       [ 0, -3, -1],
       [-1,  0, -5]])

In [37]:
a1.max(axis=1).reshape(-1,1)

array([[8],
       [9],
       [5],
       [7]])

In [39]:
exp = np.exp(a1)
exp

array([[0.00673795, 1.        , 0.36787944],
       [1.        , 0.00247875, 0.01831564],
       [1.        , 0.04978707, 0.36787944],
       [0.36787944, 1.        , 0.00673795]])

In [44]:
temp = np.exp(-20)
temp

2.061153622438558e-09

The only aspect of this function that does not directly correspond to something in the softmax equation is the subtraction of the maximum from each of the elements of X. This is done for stability reasons: when you exponentiate even large-ish numbers, the result can be quite large. numpy will return inf when you exponentiate values over 710 or so. So if values of X aren’t limited to some fixed range (e.g., [0…1]), or even if you let theta take on any value, you run the distinct possibility of hitting the inf ceiling.

But! If you subtract the maximum value from each element, the largest pre-exponential value will be zero, thus avoiding numerical instability.

So that solves the numerical stability problem, but is it mathematically correct? To clear this up, let’s write out the softmax equation with the subtraction terms in there. To keep it simple, I’ve also removed the θ parameter: