In [1]:
import numpy as np

x = [1,2,3]
y = [4,5,6]

print(type(x))
print(type(y))

<class 'list'>
<class 'list'>


In [43]:
abc = np.array([1,2,3])
pqr = np.array([4,5,6])

np.add(abc, pqr)

array([5, 7, 9])

<h3>Vectors "dot product" multiplication</h3>

In [46]:
np.dot(abc, pqr)

32

In [44]:
abc * pqr

array([ 4, 10, 18])

In [45]:
pqr / abc

array([4. , 2.5, 2. ])

In [2]:
print(x+y)

[1, 2, 3, 4, 5, 6]


In [3]:
x+y

[1, 2, 3, 4, 5, 6]

<h3>Vector Addition</h3>

In [5]:
z = np.add(x,y)
z

array([5, 7, 9])

In [6]:
type(z)

numpy.ndarray

In [7]:
mul = np.cross(x,y)
mul

array([-3,  6, -3])

In [9]:
xx = np.matrix([[1,2], [2,3]])
xx 

matrix([[1, 2],
        [2, 3]])

<h3>Matrix Mean</h3>

In [10]:
a = xx.mean(0) #row wise
a 

matrix([[1.5, 2.5]])

In [11]:
z = xx.mean(1) #column vise
z  

matrix([[1.5],
        [2.5]])

In [14]:
z.shape

(2, 1)

In [13]:
a = xx.mean()
a

2.0

In [15]:
xx

matrix([[1, 2],
        [2, 3]])

In [16]:
z

matrix([[1.5],
        [2.5]])

In [18]:
y = xx - z 
y

matrix([[-0.5,  0.5],
        [-0.5,  0.5]])

In [19]:
pp = z - xx
pp

matrix([[ 0.5, -0.5],
        [ 0.5, -0.5]])

In [20]:
x3 = np.matrix([[1,2],[4,3]])
sum1 = x3.sum()
sum1

10

In [21]:
xx.shape

(2, 2)

In [22]:
z.shape

(2, 1)

In [25]:
x4 = np.matrix([[1,2], [3,4]])
y2 = np.matrix([[3,4], [3,10]])

x4.shape

(2, 2)

In [26]:
y2.shape

(2, 2)

In [27]:
matrixadd = np.add(x4, y2)

In [28]:
matrixadd

matrix([[ 4,  6],
        [ 6, 14]])

In [29]:
x4 + y2

matrix([[ 4,  6],
        [ 6, 14]])

In [30]:
x4 - y2 

matrix([[-2, -2],
        [ 0, -6]])

In [31]:
matrixadd.shape

(2, 2)

In [33]:
x5 = np.matrix([[1,2], [4,3]])
s_sum = x5 + 1
s_sum 

matrix([[2, 3],
        [5, 4]])

In [34]:
x6 = np.matrix([[1,2], [4,3]])
s_mul = x6 * 3
s_mul

matrix([[ 3,  6],
        [12,  9]])

In [35]:
a = [[1,0], [0,1]]
b = [1,2]

np.matmul(a,b)

array([1, 2])

In [36]:
complex_mul = np.matmul([2j, 3j],[2j, 3j])
complex_mul

(-13+0j)

<h3>Matrix Transpose</h3>

In [37]:
aa = np.array([[1, 2], [3, 4]])
aa

array([[1, 2],
       [3, 4]])

In [39]:
aa.transpose()

array([[1, 3],
       [2, 4]])

In [40]:
ab = np.matrix([[1,2], [3,4]])
ab

matrix([[1, 2],
        [3, 4]])

In [41]:
ab.transpose()

matrix([[1, 3],
        [2, 4]])

<h3>Matrix, Scaler operations</h3>

In [47]:
a = np.array([[1,2], [3,4]])
a + 1

array([[2, 3],
       [4, 5]])

In [48]:
b = np.array([[1,2], [3,4]])
a + b

array([[2, 4],
       [6, 8]])

In [49]:
a - b

array([[0, 0],
       [0, 0]])

In [51]:
a = np.array([[1], [2]])

In [52]:
a

array([[1],
       [2]])

In [53]:
b = np.array([[3, 4], [5,6]])
b

array([[3, 4],
       [5, 6]])

In [55]:
c = np.array([[1,2]])

In [56]:
c

array([[1, 2]])

In [57]:
a * b

array([[ 3,  4],
       [10, 12]])

In [58]:
b * c

array([[ 3,  8],
       [ 5, 12]])

In [59]:
a * c

array([[1, 2],
       [2, 4]])

In [60]:
a.shape

(2, 1)

In [61]:
c.shape

(1, 2)

In [64]:
np.matmul(a,c)

array([[1, 2],
       [2, 4]])

In [65]:
np.dot(a,c)

array([[1, 2],
       [2, 4]])

In [66]:
a

array([[1],
       [2]])

In [67]:
b

array([[3, 4],
       [5, 6]])

In [68]:
np.add(a,b)

array([[4, 5],
       [7, 8]])

In [69]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

<h2>Tensor</h2>

In [ ]:
a